databases:
  - name: vinoteca
    ipAllowList: []
    databaseName: vinoteca_render
    plan: free
    region: frankfurt

services:
  - type: web
    name: vinoteca
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    plan: free
    region: frankfurt
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: vinoteca
          property: connectionString
# databases:
#   - name: postgres
#     ipAllowList: []
#     databaseName: vinoteca_render
#     plan: free
#     region: frankfurt

# services:
#   - type: web
#     name: vinoteca
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: "bundle exec rails s"
#     plan: free
#     region: frankfurt
#     envVars:
#       - key: RAILS_MASTER_KEY
#         sync: false
#       - key: DATABASE_URL
#         fromDatabase:
#           name: postgres
#           property: connectionString
# - type: redis
#   name: redis
#   ipAllowList: []
#   plan: free
#   maxmemoryPolicy: noeviction
## FROM BRANCH DEPLOY-RENDER-2
# databases:
#   - name: vinoteca
#     databaseName: vinoteca
#     user: vinoteca
#     plan: free

# services:
#   - type: web
#     name: vinoteca
#     runtime: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: "bundle exec puma -C config/puma.rb"
#     plan: free
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: vinoteca
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
