# databases:
#   - name: postgres
#     ipAllowList: []
#     plan: free

# services:
#   - type: web
#     name: vinoteca
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#       - key: RAILS_MASTER_KEY
#         sync: false
#       - key: DATABASE_URL
#         fromDatabase:
#           name: vinoteca
#           property: connectionString
#   # - type: redis
#   #   name: redis
#   #   ipAllowList: []
#   #   plan: free
#   #   maxmemoryPolicy: noeviction

databases:
  - name: postgress
    databaseName: vinoteca
    user: vinoteca
    plan: free

services:
  - type: web
    name: vinoteca
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vinoteca
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
