databases:
  - name: Vinoteca
    databaseName: Vinoteca
    user: Vinoteca

services:
  - type: web
    name: vinoteca
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vinoteca
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
