databases:
  - name: vinoteca
    #databaseName: vinoteca
    #user: vinoteca
    ipAllowList: []

services:
  - type: web
    name: vinoteca
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: vinoteca
          property: connectionString
    - type: redis
      name: redis
      ipAllowList: []
      plan: free
      maxmemoryPolicy: noeviction
